server:
  port: 8080
  servlet:
    context-path: /multiple-http-security-server

spring:
  datasource:
    password: root123
    url: jdbc:mysql://localhost:3306/spring_security_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root

mybatis:
  type-aliases-package: com.jonesun.multiplehttpsecurityserver.model
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    # 打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true
