server:
  port: 8080
  servlet:
    context-path: /oauth2-client

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: '2a84d0afc9ee34a4c50d'
            client-secret: '8bc700fe7c19c94c01671f29886291895368c71a'
          gitee:
            provider: gitee
            client-id: 'f08520df5414f0ab9719467c8d987f1c35026c2c2d8d3190095eaec8379f0e07'
            client-secret: 'e5ee3c0c718dec34b120ace23fd604310c13d34ffb4eef6acc88a0d44aae06e3'
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            clientName: '码云'
          keycloak:
            provider: keycloak
            client-id: oauth2-client
            client-secret: d7a1acbc-40c8-4c68-a903-b5d01dac2a35
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            clientName: 'keycloak'
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: "name"
          keycloak:
            issuer-uri: http://localhost:8083/auth/realms/jonesun
            authorization-uri: http://localhost:8083/auth/realms/jonesun/protocol/openid-connect/auth
            token-uri: http://localhost:8083/auth/realms/jonesun/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8083/auth/realms/jonesun/protocol/openid-connect/certs
            user-info-uri: http://localhost:8083/auth/realms/jonesun/protocol/openid-connect/userinfo
